### ISSUE TITLE
Crash when using existing knex instance

### ISSUE THREAD

**Issue by ricardograca** [llambda/connect-session-knex#5]
I'm trying to reuse my existing knex instance like so:

```javascript
var session = require('express-session')
var SessionStore = require('connect-session-knex')
var db = require('./lib/db') // actually a Bookshelf instance already initialized
var sessionOptions = {
  /* ... */
  store: new SessionStore({knex: db.knex})
}

app.use(session(sessionOptions))
```

But when I start the app it crashes with the following error:

```
util.js:555
  ctor.prototype = Object.create(superCtor.prototype, {
                                          ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:555:43)
    at new module.exports (/home/ricardo/src/w20-balletrosa.com/node_modules/connect-session-knex/lib/connect-session-knex.js:84:6)
...
```

connect-session-knex@1.0.8
express@4.11.2
express-session@1.10.1
knex@0.7.3

**Comment by ricardograca** [comment]
Oops... Nevermind. I forgot this little bit: 

```javascript
var SessionStore = require('connect-session-knex')(session)
```

**Comment by llambda** [comment]
Thanks for the report! I can probably add a check to improve the error message for this.

**Comment by ricardograca** [comment]
That would be a good help for noobs like me :)
