### ISSUE TITLE
UnhandledPromiseRejectionWarning when used with knex with mysql2 driver and MySQL 5.7

### ISSUE THREAD

**Issue by trphuongnam15** [llambda/connect-session-knex#66]
Sorry if this has been posted before, but Node.js gives out a warning like below every time it tries to clean up the sessions although it does successfully do so.
```
UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'nextDbCleanup' of undefined
    at D:\Projects\test\node_modules\connect-session-knex\index.js:242:31
    at <anonymous>
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Here is my setup
```javascript
const express = require('express');
const session = require('express-session');

const KnexSessionStore = require('connect-session-knex')(session);

const app = express();

const knex = require('knex')({
    client: 'mysql2',
    connection: {
        host: 'localhost',
        user: 'root',
        password: 'root',
        database: 'test'
    }
});
```
```javascript
app.use(
    session({
        secret: 'secret',
        resave: false,
        saveUninitialized: true,
        cookie: { maxAge: 36 },
        store: new KnexSessionStore({
            clearInterval: 8,
            createtable: true,
            knex: knex
        })
    })
);
```

**Comment by omarryhan** [comment]
Apologies for the inconvenience. Can you make sure you're on the latest version (V1.7.1)?

**Comment by trphuongnam15** [comment]
Oh, the problem disappeared after I'd updated to 1.7.1. Thanks for the reply!

**Comment by omarryhan** [comment]
No problem :)
